version: '2'
services:
  phabricator:
    restart: always
    ports:
     - "62443:443"
     - "62080:80"
     - "62022:22"
    volumes:
     - /srv/docker/phabricator/repos:/repos
     - /srv/docker/phabricator/extensions:/srv/phabricator/phabricator/src/extensions
    depends_on:
     - mysql
    links:
     - mysql
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_USER=root
     - MYSQL_PASS=phabricator
     - PHABRICATOR_REPOSITORY_PATH=/repos
     - PHABRICATOR_HOST=myphabricator.com:62080
     - OVERRIDE_PHABRICATOR_URI=https://github.com/huangjimmy/phabricator-1.git
     - OVERRIDE_LIBPHUTIL_URI=https://github.com/huangjimmy/libphutil.git
    image: huangsj/phabricator:20170102
     - OVERRIDE_LIBPHUTIL_BRANCH=stable
     - LANG=en_US.UTF-8
     - LC_ALL=en_US.UTF-8
     - ENABLE_APCU=true
  mysql:
    restart: always
    volumes:
     - /srv/docker/phabricator/mysql:/var/lib/mysql
     - /srv/docker/phabricator/conf/mysql:/etc/mysql/conf.d
    image: mysql:5.7.16
    environment:
     - MYSQL_ROOT_PASSWORD=phabricator